name: Build and Deploy
on: 
  workflow_dispatch: 
permissions:
  contents: read
  security-events: write
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: npm audit
        run: |
          npm install
          npm audit --audit-level=moderate
      - name: Build image
        run: |
          docker build -t myapp:latest .
      - name: Scan image with Trivy
        uses: aquasecurity/trivy-action@0.33.1
        with:
          image-ref: myapp:latest
          severity: CRITICAL
          ignore-unfixed: true
          exit-code: 1
      - name: Signin to azure
        uses: azure/login@v2
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
      - name: Push to ACR
        run: |
          az acr login -n labdeployacrstijn
          docker tag myapp:latest labdeployacrstijn.azurecr.io/myapp:latest
          docker push labdeployacrstijn.azurecr.io/myapp:latest
      - name: Deploy to WebApp
        run: |
          az webapp config container set \
          -g RGLabDeploy-Stijn \
          -n labdeploy-webapp-Stijn \
          --container-image-name labdeployacrstijn.azurecr.io/myapp:latest \
          --container-registry-url https://labdeployacrstijn.azurecr.io \
          --container-registry-user ${{secrets.ACR_USER}} \
          --container-registry-password ${{secrets.ACR_PWD}}
