name: Build and Deploy
on: 
  workflow_dispatch: 
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build image
        run: |
          docker build -t myapp:latest .
      - name: Signin to azure
        uses: azure/login@v2
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
      - name: Push to ACR
        run: |
          az acr login -n labdeployacr
          docker tag myapp:latest labdeployacr.azurecr.io/myapp:latest
          docker push labdeployacr.azurecr.io/myapp:latest
      - name: Deploy to WebApp
        run: |
          az webapp config container set \
          -g RGLabDeploy \
          -n labdeploy-webapp \
          --container-image-name labdeployacr.azurecr.io/myapp:latest \
          --container-registry-url https://labdeployacr.azurecr.io \
          --container-registry-user <USERNAME> \
          --container-registry-password <PASSWORD>
